version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mucahit
      MONGO_INITDB_ROOT_PASSWORD: 2012696MONGOdb
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/hp-disk/docker-volumes/mongodb-data
      o: bind
