version: '3.1'

services:
  s_jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    user: root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_data:/var/jenkins_home
    restart: always
