version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce
    container_name: c_portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/hp-disk/docker-volumes/portainer-data
      o: bind

